Repository dailylifev1/dailylife_front, pull requests merged in 2022-10, with the labels that each got.

#168 Feat/167 내 페이지 컴포넌트 구현 및 카드 컴포넌트 리팩토링
  src/apis/postApi.js
  src/components/card/Card.tsx
  src/components/card/CardItem.tsx
  src/components/card/useCardItem.js
  src/components/card/useCards.js
  src/components/main/Main.jsx
  src/components/myPage/MyIPage.jsx
  src/components/myPage/MyPost.jsx
  src/components/myPage/UserInfo.jsx
  src/hooks/useSetToken.js
  src/store/store.ts
Labels: feat

#170 Refactor: 카드 컴포넌트 코드 추가 및 기타 불필요 코드 제거
  src/components/card/useCardItem.js
  src/components/card/useCards.js
  src/components/navbar/navlink/writePage/WritePage.jsx
  src/hooks/usePagination.js
Labels: refactor

#174 Fix/173: ESLint 설정 변경 후 다수 에러 해결
  .eslintrc.js
  .vscode/settings.json
  package-lock.json
  package.json
  public/assets/blackHeart.png
  public/index.html
  src/App.tsx
  src/components/card/Card.tsx
  src/components/card/CardItem.tsx
  src/components/card/useCardItem.js
  src/components/card/useCards.js
  src/components/card/useCards.ts
  src/components/comments/index.jsx
  src/components/myInfo/myInfoForm/index.tsx
  src/components/navbar/navlink/writePage/WritePage.jsx
  src/components/navbar/navlink/writePage/WritePage.scss
  src/hooks/useLoginForm.js
  src/hooks/usePagination.js
  src/pages/SignUp/index.tsx
Labels: bug

#176 Refactor/171: Buttons 타입스크립트로 전환
  .eslintrc.js
  src/components/card/CardItem.tsx
  src/components/navbar/navlink/writePage/WritePage.tsx
  src/components/pagingProvider/pagingProvider.scss
  src/components/postModal/PostModal.scss
  src/hooks/useSetToken.ts
  src/pages/SignUp/index.tsx
Labels: bug

#181 chore: github pages의 homepage 경로 추가
  package.json
Labels: bug

#185 chore: 이미지 경로 수정
  src/App.tsx
  src/components/pagingProvider/pagingProvider.jsx
Labels: bug

#188 Chore/187
  public/index.html
  src/App.tsx
  src/components/card/Card.jsx
  src/components/card/useCards.ts
  src/components/myInfo/myInfoForm/MyInfoInput.tsx
  src/components/myPage/MyPage.tsx
  src/components/myPage/UserInfo.tsx
  src/components/navbar/NavLogo.tsx
  src/components/navbar/NavSearchBar.tsx
  src/components/navbar/Navlink.tsx
  src/components/navbar/PostRender.tsx
  src/components/navbar/SearchForm.tsx
  src/components/navbar/Searching.scss
  src/components/navbar/WritePage.scss
  src/components/navbar/WritePage.tsx
  src/components/navbar/index.tsx
  src/components/navbar/searching/index.tsx
  src/components/pagingProvider/pagingProvider.jsx
Labels: chore

#189 Fix/186: 게시글 작성 시 사진 업로드했을 때 워터마크가 사라지지 않는 에러 해결
  src/components/card/CardItem.tsx
  src/components/card/useCardItem.ts
  src/components/card/useCards.ts
  src/components/navbar/WritePage.scss
  src/components/navbar/WritePage.tsx
  src/components/postModal/ModalBody.tsx
Labels: bug

#192 Feat: 반응형 레이아웃을 위한 글로벌 변수 설정
  .eslintrc.js
  package.json
  public/index.html
  src/apis/userApi.ts
  src/styles/device.ts
  src/styles/theme.js
  src/styles/theme.ts
Labels: feat, style

#197 Feat/196: 서버로의 요청이 https로 가도록 수정
  public/assets/dog1.jpg
  src/App.scss
  src/common/utils.ts
  src/components/card/useCardItem.ts
  src/components/comments/index.tsx
  src/components/myInfo/myInfoForm/AccountModifyForm.tsx
  src/components/myInfo/myInfoForm/profileModifyForm.tsx
  src/components/myPage/UserInfo.tsx
  src/components/navbar/NavLogo.tsx
  src/components/postModal/WriterInfo.tsx
  src/hooks/parseComment.ts
  src/pages/SignUp/index.tsx
Labels: chore

#199 Feat/198
  src/apis/userApi.ts
  src/components/card/App.css
  src/components/card/Card.tsx
  src/components/card/CardItem.tsx
  src/components/card/Cards.scss
  src/components/myPage/MyPage.tsx
  src/components/myPage/MyPost.tsx
  src/components/myPage/UserInfo.tsx
  src/components/navbar/NavLogo.tsx
  src/hooks/useLoginForm.ts
  src/reducers/myInfo.ts
Labels: feat

#202 Feat/201: 게시글 등록 시 로딩기간 중 로딩스피너 추가
  src/apis/commentApi.ts
  src/apis/userApi.ts
  src/components/comments/CommentSection.tsx
  src/components/navbar/NavLogo.tsx
  src/components/navbar/SearchForm.tsx
  src/components/navbar/WritePage.tsx
  src/pages/SignUp/SignUpInput.tsx
  src/reducers/myInfo.ts
Labels: feat

#206 Feat/205: 이미지가 없는 게시글에서 이미지가 잘려 나오는 에러 해결
  public/assets/whiteSpace.png
  src/apis/commentApi.ts
  src/apis/postApi.ts
  src/apis/replyApi.ts
  src/components/card/CardItem.tsx
  src/components/comments/CommentSection.tsx
  src/hooks/parseComment.ts
  src/hooks/useCommentUpload.ts
Labels: bug

#209 Feat: 댓글 등록 시 로딩기간 중 로딩스피너 추가
  src/App.tsx
  src/components/Icons/SpinnerIcon.tsx
  src/components/LoadingSpinner/LoadingSpinner.tsx
  src/components/comments/CommentCreate.tsx
  src/components/login/loginForm/index.tsx
  src/components/navbar/PostRender.tsx
  src/components/navbar/WritePage.scss
  src/components/navbar/WritePage.tsx
  src/components/navbar/index.scss
  src/components/postModal/ModalContent.tsx
  src/components/postModal/PostModal.scss
  src/components/postModal/index.tsx
  src/hooks/useCommentUpload.ts
  src/hooks/useLoginForm.ts
  src/index.scss
  src/reducers/index.ts
  src/reducers/loading.ts
Labels: bug, feat

#211 fix: 회원가입 페이지 유효성검사에서 유효한 값인데 박스 배경이 빨간색인 에러 해결
  src/pages/SignUp/SignUpInput.tsx
Labels: bug

#217 Feat/216: 로그인 페이지에서 input에 정보를 입력하지 않았을 때 로그인 버튼이 비활성화 되게 구현
  src/App.tsx
  src/components/card/Card.tsx
  src/components/card/CardItem.tsx
  src/components/card/useCardItem.ts
  src/components/login/loginForm/index.tsx
  src/components/postModal/WriterInfo.tsx
  src/index.scss
  src/pages/SignUp/index.tsx
  src/reducers/selectedPostData.ts
Labels: feat

#218 Feat/216: testing console log 제거, merge conflict 해결
  src/components/login/loginForm/index.tsx
  src/components/myPage/MyPage.tsx
  src/components/myPage/UserInfo.tsx
  src/pages/SignUp/SignUpInput.tsx
Labels: chore

#228 Chore/221: 메인페이지 반응형 작업
  src/App.tsx
  src/components/card/Card.tsx
  src/components/card/CardItem.tsx
  src/components/navbar/Searching.scss
  src/components/navbar/index.scss
  src/hooks/useLoginForm.ts
  src/index.scss
  src/styles/app.styled.ts
  src/styles/device.ts
Labels: chore

#225 Refactor: WritePage CSS를 Styled component로 구현
  src/components/navbar/WritePage.scss
  src/components/navbar/WritePage.tsx
Labels: refactor

#230 Style: WritePage 컴포넌트 반응형 레이아웃 구현
  src/components/Icons/CommentIcon.tsx
  src/components/comments/Comment.tsx
  src/components/comments/CommentCreate.tsx
  src/components/comments/CommentMain.tsx
  src/components/comments/CommentSection.tsx
  src/components/comments/index.tsx
  src/components/navbar/WritePage.tsx
  src/components/postModal/ModalSocial.tsx
  src/components/postModal/PostModal.scss
  src/components/postModal/WarningModal.tsx
  src/components/postModal/WriterInfo.tsx
  src/components/postModal/index.tsx
Labels: style

#233 Style/232
  src/App.tsx
  src/components/card/CardItem.tsx
Labels: style

#237 fix: WritePage 컴포넌트 Body 자식 컴포넌트 정렬
  src/components/navbar/WritePage.tsx
Labels: bug, style
