Repository dailylifev1/dailylife_front, pull requests merged in 2022-09, with the labels that each got.

#92 Refactor/90
  .eslintrc.js
  .prettierrc
  package-lock.json
  package.json
  src/App.js
  src/App.tsx
  src/apis/client.js
  src/apis/userApi.js
  src/common/utils.js
  src/components/Icons/deleteIcon.jsx
  src/components/login/SignUp.js
  src/components/main/Main.js
  src/components/main/Main.jsx
  src/components/postModal/PostModal.js
  src/components/recentlyViewed/recentlyViewed.js
  src/components/recentlyViewed/recentlyViewed.jsx
  src/components/signUp/SignUp.jsx
  src/components/signUp/useForm.js
  src/index.js
  src/index.tsx
  src/mocks/loginFormData.js
  src/pages/Login/index.js
  src/pages/SignUp/index.js
  src/pages/index.js
  src/reportWebVitals.js
  src/setupTests.js
  tsconfig.json
Labels: refactor

#94 Refactor/91
  .eslintrc.js
  src/App.tsx
  src/apis/userApi.js
  src/components/login/Login.js
  src/components/login/SignUp.js
  src/components/login/login.css
  src/pages/Login/LoginForm/LoginBtn/index.jsx
  src/pages/Login/LoginForm/LoginFind/index.jsx
  src/pages/Login/LoginForm/LoginInput/index.jsx
  src/pages/Login/LoginForm/LoginThird/index.jsx
  src/pages/Login/LoginForm/index.jsx
  src/pages/Login/LoginForm/useLoginForm.js
  src/pages/Login/index.js
  src/pages/Login/index.jsx
  src/pages/Login/login.css
Labels: refactor

#96 Refactor/91
  .eslintrc.js
  .prettierrc
  package-lock.json
  package.json
  src/apis/userApi.js
  src/common/utils.js
  src/components/Icons/kakaoIcon.jsx
  src/components/buttons/LoginButton.jsx
  src/components/postModal/PostModal.js
  src/components/signUp/SignUp.jsx
  src/mocks/loginFormData.js
  src/mocks/signupFormData.js
  src/pages/Login/LoginForm/EasyLogin/index.jsx
  src/pages/Login/LoginForm/LoginFind/index.jsx
  src/pages/Login/LoginForm/LoginInput/index.jsx
  src/pages/Login/LoginForm/LoginThird/index.jsx
  src/pages/Login/LoginForm/index.jsx
  src/pages/Login/LoginForm/useLoginForm.js
  src/pages/Login/index.jsx
  src/pages/Login/login.css
Labels: refactor

#95 Refactor/89
  src/App.tsx
  src/apis/postApi.js
  src/components/Icons/deleteIcon.jsx
  src/components/Icons/mainLogoIcon.jsx
  src/components/UserPost/NewUserPost.js
  src/components/UserPost/UserPost.css
  src/components/UserPost/UserPost.js
  src/components/main/Main.jsx
  src/components/navbar/Navbar.js
  src/components/navbar/index.css
  src/components/navbar/index.jsx
  src/components/navbar/navLogo/navLogo.jsx
  src/components/navbar/navlink/PostRender.jsx
  src/components/navbar/navlink/navSearchBar/NavSearchBar.jsx
  src/components/navbar/navlink/navlink.jsx
  src/components/navbar/navlink/writePage/writePage.jsx
  src/components/navbar/navlink/writePage/writePage.scss
  src/components/navbar/searching/Searching.css
  src/components/navbar/searching/Searching.jsx
  src/components/search/Searching.js
Labels: refactor

#101 Refactor/97
  src/App.tsx
  src/apis/postApi.js
  src/components/card/card.js
  src/components/card/card.jsx
  src/components/card/cardItem.js
  src/components/card/cardItem.jsx
  src/components/navbar/index.jsx
  src/components/navbar/navlink/PostRender.jsx
  src/components/navbar/navlink/navlink.jsx
  src/components/navbar/navlink/writePage/writePage.jsx
  src/components/navbar/searching/Searching.jsx
  src/components/navbar/searching/searchForm/searchForm.jsx
  src/components/navbar/searching/searchForm/useAxios.js
  src/components/recentlyViewed/recentlyItem.js
  src/components/recentlyViewed/recentlyViewed.jsx
  src/components/styledComponents/Background.js
  src/components/styledComponents/Loading.js
  src/components/styledComponents/Loading.jsx
  src/components/styledComponents/Spinner.jsx
  src/pages/Login/LoginForm/index.jsx
Labels: refactor

#104 Refactor/102
  src/App.tsx
  src/components/myInfo/MyInfo.js
  src/components/myInfo/MyInfo.jsx
  src/components/myInfo/myInfoForm/myInfoForm.jsx
  src/components/myInfo/myInfoForm/useSetToken.js
Labels: refactor

#100 Refactor/99
  src/components/Icons/avatarIcon.jsx
  src/components/Icons/commentIcon.jsx
  src/components/Icons/likeIcon.jsx
  src/components/buttons/ModalCloseButton.jsx
  src/components/postModal/PostModal.js
  src/components/postModal/index.jsx
  src/components/postModal/modalBody/index.jsx
  src/components/postModal/modalBody/modalContent/commentCreate/index.jsx
  src/components/postModal/modalBody/modalContent/commentSection/commentDate/index.jsx
  src/components/postModal/modalBody/modalContent/commentSection/commentMain/index.jsx
  src/components/postModal/modalBody/modalContent/commentSection/index.jsx
  src/components/postModal/modalBody/modalContent/index.jsx
  src/components/postModal/modalBody/modalContent/modalSocial/index.jsx
  src/components/postModal/modalBody/modalContent/writerInfo/index.jsx
  src/components/postModal/modalBody/modalImage/index.jsx
  src/components/postModal/postModal.css
Labels: refactor

#103 Refactor/93
  .eslintrc.js
  src/App.test.js
  src/apis/userApi.js
  src/common/utils.js
  src/components/signUp/InputInfo.jsx
  src/components/signUp/SignUp.jsx
  src/components/signUp/useForm.js
  src/index.tsx
  src/styles/GlobalStyle.jsx
Labels: feat

#106 Refactor/99
  src/components/Pagination/Pagination.js
  src/components/Pagination/Pagination.jsx
  src/components/card/card.jsx
  src/components/main/Main.jsx
  src/components/postModal/index.jsx
  src/components/postModal/modalBody/index.jsx
  src/components/postModal/modalBody/modalContent/commentCreate/index.jsx
  src/components/postModal/modalBody/modalContent/commentSection/commentDate/index.jsx
  src/components/postModal/modalBody/modalContent/commentSection/commentMain/index.jsx
  src/components/postModal/modalBody/modalContent/commentSection/index.jsx
  src/components/postModal/modalBody/modalContent/index.jsx
  src/components/postModal/modalBody/modalContent/modalSocial/index.jsx
Labels: refactor

#110 Refactor/109
  src/App.tsx
  src/apis/postApi.js
  src/common/utils.js
  src/components/Icons/closeButtonIcon.jsx
  src/components/Icons/kebabMenu.jsx
  src/components/Icons/postModalCloseButtonIcon.jsx
  src/components/Pagination/Pagination.css
  src/components/Pagination/Pagination.jsx
  src/components/Pagination/usePagination.js
  src/components/buttons/ModalCloseButton.jsx
  src/components/buttons/kebabMenuButton.jsx
  src/components/card/Cards.css
  src/components/card/card.jsx
  src/components/card/cardItem.jsx
  src/components/card/index.jsx
  src/components/main/Main.jsx
  src/components/navbar/index.jsx
  src/components/navbar/navlink/writePage/writePage.jsx
  src/components/navbar/navlink/writePage/writePage.scss
  src/components/pagingProvider/pagingProvider.jsx
  src/components/postModal/index.jsx
  src/components/postModal/modalBody/modalContent/index.jsx
  src/components/postModal/modalBody/modalContent/writerInfo/index.jsx
  src/components/postModal/modalBody/modalImage/index.jsx
  src/components/postModal/postModal.css
  src/components/signUp/SignUp.jsx
  src/reducers/post.js
Labels: refactor, feat

#113 Refactor/111
  .eslintrc.js
  .prettierrc
  package-lock.json
  package.json
  src/App.tsx
  src/apis/commentApi.js
  src/apis/postApi.js
  src/apis/replyApi.js
  src/components/Icons/avatarIcon.jsx
  src/components/Icons/commentIcon.jsx
  src/components/Icons/likeIcon.jsx
  src/components/buttons/DeleteCommentbutton.jsx
  src/components/buttons/ModalCloseButton.jsx
  src/components/buttons/ReplyOptionButton.jsx
  src/components/buttons/kebabMenuButton.jsx
  src/components/card/card.jsx
  src/components/comments/commentCreate/index.jsx
  src/components/comments/commentCreate/useCommentUpload.js
  src/components/comments/commentSection/comment/CommentDate.jsx
  src/components/comments/commentSection/comment/CommentMain.jsx
  src/components/comments/commentSection/comment/ReplyList.jsx
  src/components/comments/commentSection/comment/index.jsx
  src/components/comments/commentSection/index.jsx
  src/components/comments/index.jsx
  src/components/main/Main.jsx
  src/components/myInfo/MyInfo.jsx
  src/components/myInfo/myInfoForm/myInfoForm.jsx
  src/components/navbar/index.jsx
  src/components/navbar/navLogo/navLogo.jsx
  src/components/navbar/navlink/PostRender.jsx
  src/components/navbar/navlink/navlink.jsx
  src/components/navbar/navlink/writePage/writePage.jsx
  src/components/navbar/searching/Searching.jsx
  src/components/navbar/searching/searchForm/searchForm.jsx
  src/components/pagingProvider/pagingProvider.jsx
  src/components/postModal/PostModal.scss
  src/components/postModal/index.jsx
  src/components/postModal/modalBody/modalContent/commentSection/commentDate/index.jsx
  src/components/postModal/modalBody/modalContent/commentSection/index.jsx
  src/components/postModal/modalBody/modalContent/index.jsx
  src/components/postModal/modalBody/modalContent/modalSocial/index.jsx
  src/components/postModal/modalBody/modalContent/writerInfo/index.jsx
  src/components/signUp/SignUp.jsx
  src/hooks/useAxios.js
  src/hooks/useCommentHearts.jsx
  src/hooks/useComments.js
  src/hooks/useForm.js
  src/hooks/useLoginForm.js
  src/hooks/usePagination.js
  src/hooks/useSetToken.js
  src/index.tsx
  src/mocks/postData.js
  src/pages/Login/LoginForm/EasyLogin/index.jsx
  src/pages/Login/LoginForm/index.jsx
  src/reducers/myInfo.js
  src/styles/GlobalStyle.jsx
  src/styles/theme.js
Labels: refactor

#120 프로필 업데이트 페이지 재사용 컴포넌트 구현
  .eslintrc.js
  package-lock.json
  package.json
  src/App.tsx
  src/common/utils.js
  src/components/Icons/AvatarIcon.jsx
  src/components/Icons/AvatarIcon.tsx
  src/components/Icons/MyPageIcon.jsx
  src/components/Icons/SpinnerIcon.jsx
  src/components/Icons/WritePageButton.jsx
  src/components/Pagination/Pagination.jsx
  src/components/buttons/DeleteCommentbutton.jsx
  src/components/buttons/ModalCloseButton.jsx
  src/components/buttons/MyInfoButton.tsx
  src/components/buttons/ProfileMenuItem.tsx
  src/components/card/Card.jsx
  src/components/card/CardItem.jsx
  src/components/comments/Comment.jsx
  src/components/comments/CommentCreate.jsx
  src/components/comments/CommentDate.jsx
  src/components/comments/CommentMain.jsx
  src/components/comments/CommentSection.jsx
  src/components/comments/ReplyList.jsx
  src/components/comments/index.jsx
  src/components/login/loginForm/index.jsx
  src/components/main/Main.jsx
  src/components/myInfo/MyInfo.jsx
  src/components/myInfo/myInfoForm/MyInfoForm.jsx
  src/components/myInfo/myInfoForm/MyInfoInput.tsx
  src/components/myInfo/myInfoForm/MyInfoTitle.tsx
  src/components/myInfo/myInfoForm/index.tsx
  src/components/myInfo/myinfo.css
  src/components/myInfo/myinfo.scss
  src/components/navbar/index.css
  src/components/navbar/navlink/Navlink.jsx
  src/components/navbar/navlink/PostRender.jsx
  src/components/navbar/navlink/writePage/WritePage.jsx
  src/components/navbar/navlink/writePage/WritePage.scss
  src/components/postModal/ModalBody.jsx
  src/components/postModal/ModalContent.jsx
  src/components/postModal/ModalImage.jsx
  src/components/postModal/ModalSocial.jsx
  src/components/postModal/PostModal.scss
  src/components/postModal/WriterInfo.jsx
  src/components/postModal/index.jsx
  src/hooks/useCommentUpload.js
  src/hooks/useComments.js
  src/hooks/useLoginForm.js
  src/reducers/authToken.js
  src/reducers/comment.js
  src/reducers/index.js
  src/reducers/kebab.postModal.js
  src/reducers/myInfo.js
  src/reducers/post.js
  src/reducers/searchResult.js
  src/reducers/selectedPostData.js
  src/store/store.js
Labels: feat

#124 Feat: 프로필 이미지 미리보기
  src/components/Icons/AvatarIcon.tsx
  src/components/myInfo/myInfoForm/index.tsx
  src/reducers/index.js
Labels: bug

#126 Fix: kebab메뉴가 닫히지 않는 문제 해결
  src/reducers/index.js
Labels: bug

#128 Fix: myInfoForm 레이아웃 수정
  src/App.tsx
  src/common/utils.js
  src/components/buttons/ModalCloseButton.jsx
  src/components/buttons/MyInfoButton.tsx
  src/components/buttons/ProfileMenuItem.tsx
  src/components/card/CardItem.jsx
  src/components/comments/CommentList.jsx
  src/components/comments/CommentMain.jsx
  src/components/myInfo/MyInfo.tsx
  src/components/myInfo/myInfoForm/AccountModifyForm.tsx
  src/components/myInfo/myInfoForm/MyInfoInput.tsx
  src/components/myInfo/myInfoForm/accountManage.scss
  src/components/myInfo/myInfoForm/index.tsx
  src/components/myInfo/myInfoForm/profileMenu.tsx
  src/components/myInfo/myInfoForm/profileModifyForm.tsx
  src/components/myInfo/myinfo.scss
  src/components/postModal/ModalBody.jsx
  src/hooks/useCommentUpload.js
  src/hooks/useComments.js
Labels: feat

#130 Fix: MyInfoInput에 validate 버그
  src/App.tsx
  src/components/myInfo/myInfoForm/MyInfoInput.tsx
Labels: bug

#135 Fix: getBoard 요청 경로 수정
  src/App.tsx
  src/apis/postApi.js
  src/components/Pagination/Pagination.jsx
  src/components/Pagination/usePagination.js
  src/components/card/Card.jsx
  src/components/card/CardItem.jsx
  src/components/card/Cards.scss
  src/components/navbar/index.jsx
  src/components/navbar/index.scss
  src/components/navbar/navlink/PostRender.jsx
  src/components/navbar/searching/Searching.scss
  src/components/navbar/searching/searchForm/SearchForm.jsx
  src/components/pagingProvider/PagingProvider.jsx
  src/components/pagingProvider/pagingProvider.scss
  src/hooks/usePagination.js
  src/index.scss
  src/index.tsx
  src/pages/Login/index.jsx
  src/pages/Login/login.scss
Labels: bug

#144 Chore/143: 게시글 modal에서 KebabMenu를 연 상태로 다시 클릭 시 닫히게 수정
  public/assets/avatarImg.png
  public/assets/dog1.jpg
  public/assets/error_icon.png
  public/assets/message.png
  public/assets/profile.png
  public/assets/star.png
  public/assets/viewed.png
  public/assets/갱지2.jpg
  public/assets/갱지3.jpg
  public/assets/갱지4.png
  public/assets/갱지5.jpg
  public/assets/갱지6.jpg
  src/App.tsx
  src/common/utils.js
  src/components/Icons/AvatarIcon.tsx
  src/components/buttons/ModalCloseButton.jsx
  src/components/buttons/MyInfoButton.tsx
  src/components/buttons/SubmitButton.tsx
  src/components/card/Card.jsx
  src/components/card/CardItem.jsx
  src/components/comments/CommentCreate.jsx
  src/components/main/Main.jsx
  src/components/myInfo/myInfoForm/AccountModifyForm.tsx
  src/components/myInfo/myInfoForm/profileModifyForm.tsx
  src/components/myInfo/myinfo.scss
  src/components/navbar/index.scss
  src/components/navbar/navlink/PostRender.jsx
  src/components/navbar/navlink/writePage/WritePage.jsx
  src/components/pagingProvider/Pagination.jsx
  src/components/postModal/ModalBody.jsx
  src/components/postModal/PostModal.scss
  src/components/postModal/WarningModal.tsx
  src/components/postModal/WriterInfo.jsx
  src/components/warningModal/WarningModal.tsx
  src/pages/SignUp/SignUpInput.tsx
  src/pages/SignUp/index.jsx
  src/pages/SignUp/index.tsx
  src/pages/SignUp/signUp.scss
  src/pages/index.js
Labels: chore, style

#151 Refactor: Redux store reducer 타입스크립트로 교체
  .eslintrc.ts
  src/components/buttons/DeleteCommentbutton.tsx
  src/components/myInfo/myInfoForm/AccountModifyForm.tsx
  src/components/navbar/navlink/writePage/WritePage.jsx
  src/components/pagingProvider/PagingProvider.jsx
  src/components/postModal/PostModal.scss
  src/hooks/useLoginForm.js
  src/index.tsx
  src/pages/SignUp/SignUpInput.tsx
  src/reducers/comment.ts
  src/reducers/index.ts
  src/reducers/kebab.postModal.ts
  src/reducers/myInfo.js
  src/reducers/myInfo.ts
  src/reducers/post.js
  src/reducers/post.ts
  src/reducers/searchResult.js
  src/reducers/searchResult.ts
  src/reducers/selectedPostData.ts
  src/store/hooks.ts
  src/store/store.ts
Labels: refactor

#148 chore: Warning form 구현
  src/components/Icons/LikeIcon.jsx
  src/components/buttons/DeleteCommentbutton.tsx
  src/components/card/Card.tsx
  src/components/card/CardItem.tsx
  src/components/main/Main.jsx
  src/components/postModal/index.jsx
  src/components/warningModal/WarningModal.tsx
  src/pages/SignUp/index.jsx
  src/pages/SignUp/index.tsx
  src/reducers/authToken.js
  src/reducers/authToken.ts
  src/reducers/comment.ts
  src/reducers/post.ts
Labels: chore

#153 Fix: 검색 시 페이징 버그 수정
  src/components/card/Card.tsx
  src/components/card/CardItem.tsx
  src/components/main/Main.jsx
  src/components/navbar/searching/searchForm/SearchForm.jsx
  src/components/pagingProvider/PagingProvider.jsx
  src/hooks/usePagination.js
  src/index.tsx
  src/reducers/post.ts
  src/reducers/searchResult.ts
Labels: bug

#154 Fix/152: 게시물 등록 버튼을 누를 시 에러 해결
  src/components/card/Card.tsx
  src/components/card/CardItem.tsx
  src/components/card/index.jsx
  src/components/navbar/index.jsx
  src/components/navbar/navlink/Navlink.jsx
  src/components/navbar/navlink/PostRender.jsx
  src/components/navbar/navlink/writePage/WritePage.jsx
  src/components/navbar/searching/searchForm/SearchForm.jsx
  src/hooks/useComments.js
  src/reducers/post.ts
Labels: bug

#156 Fix: 게시물 검색시 페이지수가 바뀌지 않는 버그 해결
  src/apis/client.ts
  src/apis/postApi.ts
  src/components/card/CardItem.tsx
  src/components/navbar/searching/searchForm/SearchForm.jsx
  src/hooks/usePagination.js
  src/reducers/post.ts
Labels: bug

#159 Fix/158: navBar UI가 피그마 시안과 다른 것 수정
  src/components/card/Cards.scss
  src/components/navbar/index.jsx
  src/components/navbar/index.scss
  src/components/navbar/navLogo/NavLogo.jsx
  src/components/navbar/navlink/PostRender.jsx
  src/components/navbar/navlink/navSearchBar/NavSearchBar.jsx
  src/components/navbar/searching/Searching.scss
  src/components/navbar/searching/index.jsx
  src/components/navbar/searching/searchForm/SearchForm.jsx
  src/components/pagingProvider/PagingProvider.jsx
  src/hooks/useLoginForm.js
  src/index.scss
Labels: style

#163 Chore/162: 게시글 card를 피그마 시안대로 수정
  package-lock.json
  package.json
  src/App.tsx
  src/components/card/CardItem.tsx
  src/components/navbar/searching/Searching.scss
  src/reducers/post.ts
Labels: chore
